name: Build Zed Windows

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00 构建一次

jobs:
  build-windows:
    runs-on: windows-latest

    env:
      # 缩短 cargo 路径，避免 Windows 上路径过长
      CARGO_HOME: C:\cargo
      CARGO_TARGET_DIR: C:\target

    steps:
      - uses: actions/checkout@v4

      - name: Enable long paths support
        run: |
          git config --system core.longpaths true
          reg add "HKLM\SYSTEM\CurrentControlSet\Control\FileSystem" /v LongPathsEnabled /t REG_DWORD /d 1 /f

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Add Windows target
        run: rustup target add x86_64-pc-windows-msvc

      - name: Build (Release)
        run: cargo build --release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zed-windows-release
          path: C:\target\release\*

      - name: Create GitHub Release
        if: github.event_name == 'push' || github.event_name == 'schedule'
        uses: ncipollo/release-action@v1
        with:
          tag: nightly-${{ github.run_number }}
          name: "Zed Windows Build #${{ github.run_number }}"
          artifacts: "C:/target/release/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
