name: Build Zed Windows

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00 构建一次

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Add Windows target
        run: rustup target add x86_64-pc-windows-msvc

      - name: Build (Release)
        run: cargo build --release

      - name: Run tests
        run: cargo test --workspace

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zed-windows-release
          path: target/release/*

      - name: Create GitHub Release
        if: github.event_name == 'push' || github.event_name == 'schedule'
        uses: ncipollo/release-action@v1
        with:
          tag: nightly-${{ github.run_number }}
          name: "Zed Windows Build #${{ github.run_number }}"
          artifacts: "target/release/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true   # 如果 tag 已存在，允许覆盖
